# Generated by Django 5.2.7 on 2025-10-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0002_profile_email_profile_password_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
