# Generated by Django 5.2.7 on 2025-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0008_banlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
