# Generated by Django 5.2.7 on 2025-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0010_post_rejection_reason_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
