# Generated by Django 5.2.7 on 2025-10-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0013_chatmessage_chatnotification_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
    ]
