# Generated by Django 5.2.7 on 2025-10-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0014_alter_chatmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
