# Generated by Django 5.2.7 on 2025-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0019_category_province_state_post_category_post_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Hosanq',
        ),
        migrations.AddField(
            model_name='category',
            name='par',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
