# Generated by Django 5.2.7 on 2025-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0021_alter_category_options_rename_hosanq_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('state', 'name')},
        ),
    ]
