# Generated by Django 5.2.7 on 2025-10-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0022_alter_state_name_alter_province_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kognem.province'),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kognem.state'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
