# Generated by Django 5.2.7 on 2025-10-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0023_alter_post_province_alter_post_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Profession',
        ),
    ]
