# Generated by Django 5.2.7 on 2025-10-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0024_rename_category_profession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='Category',
        ),
    ]
