# Generated by Django 5.2.7 on 2025-11-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0028_post_cancelled_by_user_post_worker_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_status',
            field=models.CharField(choices=[('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting for Owner Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='open', max_length=20),
        ),
    ]
