# Generated by Django 5.2.7 on 2025-11-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0029_alter_post_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='disputed_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='disputed_by_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resolved_by_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='support_resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
