# Generated by Django 5.2.7 on 2025-11-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0031_userloginhistory_userregistrationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginhistory',
            options={'ordering': ['-login_time'], 'verbose_name_plural': 'User Login Histories'},
        ),
    ]
