# Generated by Django 5.2.7 on 2025-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0032_alter_userloginhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
