# Generated by Django 5.2.7 on 2025-11-04 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0034_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('worker_to_owner', 'Worker to Task Owner'), ('owner_to_worker', 'Owner to Worker')], max_length=20, verbose_name='Review Type')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ - Poor'), (2, '⭐⭐ - Fair'), (3, '⭐⭐⭐ - Good'), (4, '⭐⭐⭐⭐ - Very Good'), (5, '⭐⭐⭐⭐⭐ - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star Rating')),
                ('comment', models.TextField(blank=True, help_text='Share your experience working with this person (optional)', null=True, verbose_name='Review Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Mark if this review is verified (not spam)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Kognem.post', verbose_name='Task Post')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed User')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'reviewer'], name='Kognem_revi_post_id_c67a80_idx'), models.Index(fields=['reviewed_user', 'created_at'], name='Kognem_revi_reviewe_68ac56_idx'), models.Index(fields=['rating', 'is_verified'], name='Kognem_revi_rating_c68ad7_idx'), models.Index(fields=['review_type'], name='Kognem_revi_review__5fa907_idx')],
                'unique_together': {('post', 'reviewer', 'review_type')},
            },
        ),
    ]
