# Generated by Django 5.2.7 on 2025-11-04 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0035_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('worker_completed_owner_incomplete', 'Worker marked completed, Owner marked incomplete'), ('owner_disputed_completion', 'Owner disputed worker completion'), ('worker_disputed_incomplete', 'Worker disputed incomplete status')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('worker_evidence', models.TextField(blank=True, help_text="Worker's evidence for completion", null=True)),
                ('owner_evidence', models.TextField(blank=True, help_text="Owner's evidence for incompletion", null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('other_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_disputes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='Kognem.post')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Dispute',
                'verbose_name_plural': 'Task Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
