# Generated by Django 5.2.7 on 2025-11-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0036_taskdispute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_status',
            field=models.CharField(choices=[('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting for Owner Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('under_review', 'Under Admin Review')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='dispute_type',
            field=models.CharField(choices=[('worker_completed_owner_incomplete', 'Worker marked completed, Owner marked incomplete'), ('worker_disputed_incomplete', 'Worker disputed incomplete status'), ('owner_disputed_completion', 'Owner disputed worker completion'), ('direct_message', 'Direct message to admin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='other_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='dispute_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Kognem.taskdispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
