# Generated by Django 5.2.7 on 2025-11-04 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0037_alter_post_task_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdispute',
            name='dispute_type',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='other_party',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='owner_evidence',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='worker_evidence',
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('reopened', 'Reopened')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_disputes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_disputes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes visible to both parties', null=True),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='reason',
            field=models.TextField(default=1, help_text='Detailed reason for the dispute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('reopened', 'Reopened')], default='under_review', max_length=20),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_evidence/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='Kognem.taskdispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
