# Generated by Django 5.2.7 on 2025-11-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0038_remove_taskdispute_dispute_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_status',
            field=models.CharField(choices=[('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting for Owner Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('under_review', 'Under Admin Review'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='open', max_length=20),
        ),
    ]
