# Generated by Django 5.2.7 on 2025-11-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0039_alter_post_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisputeEvidence',
        ),
    ]
