# Generated by Django 5.2.7 on 2025-11-04 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0040_delete_disputeevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdispute',
            name='admin_decision',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskdispute',
            name='worker',
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='dispute_type',
            field=models.CharField(choices=[('worker_completed_owner_incomplete', 'Worker marked completed, Owner marked incomplete'), ('worker_disputed_incomplete', 'Worker disputed incomplete status'), ('owner_disputed_completion', 'Owner disputed worker completion'), ('direct_message', 'Direct message to admin')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='initiated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='other_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='owner_evidence',
            field=models.TextField(blank=True, help_text="Owner's evidence for incompletion", null=True),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='worker_evidence',
            field=models.TextField(blank=True, help_text="Worker's evidence for completion", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='task_status',
            field=models.CharField(choices=[('open', 'Open for Applications'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting for Owner Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('under_review', 'Under Admin Review')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskdispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
    ]
