# Generated by Django 5.2.7 on 2025-11-07 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0041_remove_taskdispute_admin_decision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputemessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Dispute Message', 'verbose_name_plural': 'Dispute Messages'},
        ),
        migrations.AddField(
            model_name='disputemessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='admin_decision',
            field=models.CharField(blank=True, choices=[('completed', 'Mark as Completed'), ('cancelled', 'Cancel Task'), ('refunded', 'Full Refund'), ('split', 'Split Payment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='owner_percentage',
            field=models.IntegerField(default=50, help_text='Percentage for owner (0-100)'),
        ),
        migrations.AddField(
            model_name='taskdispute',
            name='worker_percentage',
            field=models.IntegerField(default=50, help_text='Percentage for worker (0-100)'),
        ),
        migrations.AlterField(
            model_name='disputemessage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='dispute_messages/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='dispute_evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_initial', models.BooleanField(default=False, help_text='Whether this is initial evidence submitted with dispute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='Kognem.taskdispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
