# Generated by Django 5.2.7 on 2025-11-09 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0042_alter_disputemessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='dispute_messages/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Kognem.disputemessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
