# Generated by Django 5.2.7 on 2025-11-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kognem', '0044_delete_disputemessageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdispute',
            name='dispute_resolved',
            field=models.BooleanField(default=False, help_text='Whether the dispute has been resolved by admin'),
        ),
    ]
